[package]
name = "fav-genre"
version = "0.1.0"
authors = ["Joshua Maros <60271685+joshua-maros@users.noreply.github.com>"]
edition = "2018"

[dependencies]
scones = "^0.1.2"

[dependencies.bevy]
version = "0.4.0"
features = ["dynamic"] # Enable faster iterative compilation times.
